set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,tmux-256color:RGB,screen-256color:RGB"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000

set -g mouse on
set -s set-clipboard on
setw -g mode-keys vi
setw -g aggressive-resize on

set -sg escape-time 10
set -g focus-events on
set -g allow-passthrough on
set -g status-position top
set -g update-environment "DISPLAY KRB5CCNAME SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY PATH"

bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"
bind -r f display-popup -E "~/dotfiles/bin/tmux-sessionizer"
bind S setw synchronize-panes

set -g status-style "bg=black,fg=white"
set -g status-left ""
set -g status-right '#[fg=white,bg=black,bold] %m/%d #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
setw -g window-status-current-style "bg=white,fg=black"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
run-shell '/Users/basrawi/Documents/projects/tmux-prayer-plugin/tmux-prayer-plugin.tmux'
run '~/.tmux/plugins/tpm/tpm'
