vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.winborder = "single"
vim.g.have_nerd_font = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.wrap = true
vim.o.linebreak = true
vim.o.tabstop = 4
vim.o.swapfile = false
vim.o.cursorline = true
vim.o.cursorcolumn = false
vim.opt.colorcolumn = "80,120"
vim.opt.updatetime = 250
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.breakindent = true
vim.o.shiftwidth = 2
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.incsearch = true
vim.o.signcolumn = "yes"
vim.o.clipboard = "unnamedplus"
vim.o.autoread = true
vim.o.mouse = "a"
vim.o.splitright = true
vim.o.splitbelow = true
vim.opt.completeopt:append({ "menuone", "noselect", "popup" })
