- name: Ensure Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_installed
  ignore_errors: yes

- name: Install Homebrew if not present
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew # Adjust this based on your system
  when: homebrew_installed.rc != 0
  become: no

- name: Install software with Homebrew
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - azure-cli
    - btop
    - fzf
    - font-hack-nerd-font
    - bat
    - crane
    - kubectl
    - jq
    - git
    - go
    - neovim
    - podman
    - tree
    - wezterm
    - z
  become: no # Do not use sudo
